runtime: python37
instance_class: F4
automatic_scaling:
  min_instances: 1
  max_instances: 20
  min_idle_instances: 1
inbound_services:
- warmup
entrypoint: gunicorn -b :$PORT arrow.server:app --worker-class sanic.worker.GunicornWorker --timeout 120
